### ISSUE TITLE
Missing pymemcache python module 

### ISSUE THREAD

**Issue by CyrusNchege** [maniamartial/EmployNanny#96]
Pymemcache is missing from `requirements.txt`  and brings an error when running `python manage.py migrate`
![Screenshot from 2023-10-21 12-59-13](https://github.com/maniamartial/EmployNanny/assets/98806241/20347cdf-650e-4d6c-a9b5-9db8a00969b8)

**Comment by maniamartial** [comment]
Requirements.txt modules varies depending on the OS you are using. So you are to install that in your end. 
Just install "pip install pymemcache"
I think the problem will dissapear

**Comment by CyrusNchege** [comment]
I have created a pull request

**Comment by maniamartial** [comment]
Merged, hope everything is done, we can close the issue
