### ISSUE TITLE
Addition of save jobs

### ISSUE THREAD

**Issue by maniamartial** [maniamartial/EmployNanny#98]
We can add save job., a feature where nanny can save a job and access it earlier.

**Comment by maniamartial** [comment]
Done by @faisalepty .
I appreciate

**Comment by maniamartial** [comment]
Then we got a bug, think of worst case scenario where unregistered member clicks on save job button.

![1worst_case](https://github.com/maniamartial/EmployNanny/assets/60258622/1395bbbc-9df8-4930-a74d-84ee1c44cba9)

Can we include the @login_required on top of the save job function. Let me know your idea
Alternatively, make use of try{}except to catch any error. 
Remember clients need not to see an bug(assuming it's in business world).
@faisalepty

**Comment by maniamartial** [comment]
Ensure you merge my current master with your forked repo before you make such changes.

**Comment by maniamartial** [comment]
Also we can use this approach, just make the navbar link 'saved jobs' to be visible to nannies who have logged in and not everyone.

**Comment by faisalepty** [comment]
> `
```python
@login_required
def save_job(request, job_id):
    user = request.user
    saved = SavedJobModel.objects.filter(user=user)
    previous_page = request.META.get('HTTP_REFERER', None)
    job = jobModel.objects.get(id=job_id)
    save, created = SavedJobModel.objects.get_or_create(user=user, job=job)
    return redirect(previous_page)
   
``` `

I worked on the bug

**Comment by maniamartial** [comment]
Thanks, @faisalepty
